### ISSUE TITLE
Stack overflow when creating world 1.21.1

### ISSUE THREAD

**Issue by Zelly9191** [Alexandra-Myers/Atlas-Core#4]
getting a stack overflow in Neoforge Minecraft 1.21.1 when creating a world with this mod :(

latest.log(tail): https://gnomebot.dev/paste/mclogs/Jx7F4vv (~16MB & ~117k lines)

[latest.log](https://github.com/user-attachments/files/24320551/latest.log)

**Comment by Zelly9191** [comment]
1.1.2 beta 5.1 so the latest for 1.21.1

**Comment by Alexandra-Myers** [comment]
oh I fixed it on 1.20.1 only

**Comment by Alexandra-Myers** [comment]
I'll get to work on that after Christmas

**Comment by Zelly9191** [comment]
Hey sorry to bug you. I just wanted to remind you in case you forgot after all the holiday hubbub. My apologies if I'm nagging I'm not trying to. As always, take your time. I'm just wondering if you've had any luck?

**Comment by Zelly9191** [comment]
Is there anything I can do to help?

**Comment by Zelly9191** [comment]
Huh that's really weird. Im guessing it wont be a simple fix of porting the changes then sadly :(

**Comment by Alexandra-Myers** [comment]
nah it is that easy
